### ISSUE TITLE
Document Publishing Workflow

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#4] opened 2017-06-07 18:40 UTC
Add documentation in README for how folks can contribute to the site.

**Comment by amandavisconti** [comment] 2017-06-08 15:52
Social media workflow => IFTTT-style post to Twitter within specific time range? (8am-12pm EST)
Scoop Tramebot
Ping people when new post added (in case needs formatting improvement/etc.)

**Comment by walshbr** [comment] 2018-02-13 19:41
Duplicate of #64 #90

**Closed by walshbr** 2018-02-13 19:41 UTC
Labels: documentation
