### ISSUE TITLE
No blog posts appearing on /blog!

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#453] opened 2018-09-06 15:28 UTC
See http://maybe.scholarslab.org/blog/ (the header blurb is appearing, but no posts are listed)

**Comment by walshbr** [comment] 2018-09-06 15:34
This is a duplicate of #438 @amandavisconti. It's because we're using a gem for the paginating not whitelisted by GitHub. We'll need to either move off GitHub for hosting or change the gem. Probably the former.

**Closed** 2018-09-06 15:50 UTC
Labels: bug, design/dev
